-- generated by scripts/generate-seed-meals-sql.mjs
create table if not exists meal_seeds (
  id bigint generated always as identity primary key,
  slug text unique not null,
  title text not null,
  region text not null default 'CO',
  skill_level text not null,
  prep_time_min int not null,
  slot text not null default 'lunch',
  tags text[] not null default '{}'::text[],
  created_at timestamptz not null default now()
);

insert into meal_seeds (slug, title, region, skill_level, prep_time_min, slot, tags)
values
('ajiaco-rapido', 'Quick ajiaco', 'CO', 'Beginner', 35, 'lunch', '{"soup","colombian","chicken","potato"}'),
('pollo-criollo-bowl', 'Creole chicken bowl', 'CO', 'Beginner', 30, 'lunch', '{"bowl","colombian","rice","chicken"}'),
('lentejas-arroz', 'Lentils with rice', 'CO', 'Intermediate', 40, 'lunch', '{"legumes","comfort","rice"}'),
('sudado-res', 'Beef stew', 'CO', 'Intermediate', 45, 'lunch', '{"stew","beef","potato"}'),
('ensalada-tibio-atun', 'Warm tuna salad', 'CO', 'Beginner', 20, 'lunch', '{"salad","fish","quick"}'),
('tilapia-horno', 'Baked tilapia', 'CO', 'Beginner', 30, 'lunch', '{"fish","baked","quick"}'),
('sancocho-express', 'Express sancocho', 'CO', 'Advanced', 50, 'lunch', '{"soup","colombian","roots"}'),
('curry-garbanzos', 'Mild chickpea curry', 'CO', 'Intermediate', 35, 'lunch', '{"legumes","stew","vegetarian"}')
on conflict (slug) do update set
  title = excluded.title,
  region = excluded.region,
  skill_level = excluded.skill_level,
  prep_time_min = excluded.prep_time_min,
  slot = excluded.slot,
  tags = excluded.tags;
